<a href="https://colab.research.google.com/github/tn-220/SIC-Machine-Learning/blob/main/SIC_ML_Coding_Exercises/SIC_ML_Chapter_03_Coding_Exercises/ex_0203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Coding Exercise #0203

### 1. Doing linear algebra with NumPy arrays:

In [1]:
import numpy as np

#### 1.1. Vectors:

In [2]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [3]:
x + y

array([ 3,  7, 11])

In [4]:
x - y

array([-1, -1, -1])

The following operations are possible in NumPy but not in linear algebra:

In [5]:
x * y

array([ 2, 12, 30])

In [6]:
x / y

array([0.5       , 0.75      , 0.83333333])

Internal product with dot():

In [7]:
np.dot(x,y)

44

In [8]:
x.dot(y)

44

In [9]:
y.dot(x)

44

In [10]:
np.sum(x*y)

44

#### 1.2. Creating matrices:

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.random.seed(222)
np.random.random((2,2))   # Return random floats in the half-open interval [0.0, 1.0)

array([[0.52602843, 0.68531719],
       [0.83567419, 0.65376526]])

In [40]:
np.random.seed(111)
x = np.random.randn(1000,1000)    # Return a sample (or samples) from the “standard normal” distribution.
print(x.mean())
print(x.std())

-0.0019638616576093757
0.9987442197017593


In [41]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [16]:
print(np.fliplr(arr))

[[0 0 0 0 1]
 [0 0 0 2 0]
 [0 0 3 0 0]
 [0 4 0 0 0]
 [5 0 0 0 0]]


In [17]:
print(np.diagonal(arr))

[1 2 3 4 5]


#### 1.3. Matrix operations:

Matrix addition, subtraction and multiplication:

In [18]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])
print(m1, "\n")
print(m2)

[[1 2 3]
 [4 5 6]] 

[[6 5 4]
 [3 2 1]]


In [19]:
m1 + m2

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
m1 - m2

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [21]:
np.transpose(m2)

array([[6, 3],
       [5, 2],
       [4, 1]])

In [43]:
m2.T

array([[6, 3],
       [5, 2],
       [4, 1]])

In [57]:
m3 = np.array([1,2,3,4]).reshape(2,2)
m4 = np.linalg.inv(m3)
np.round(np.dot(m3, m4),10)

array([[1., 0.],
       [0., 1.]])

Matrix multiplication with dot():

In [22]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

In [58]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [59]:
print(y.dot(x))

[[44]]


In [61]:
print(y.dot(x).shape)

(1, 1)


In [25]:
y.dot(x)[0,0]

44

In [26]:
x.dot(y)

array([[ 2,  4,  6],
       [ 6, 12, 18],
       [10, 20, 30]])

The following operations are possible in NumPy but not in linear algebra:

In [27]:
m1 * m2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [62]:
(m1 * m2).shape

(2, 3)

In [28]:
m1 / m2

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

Operations involving matrix and scalar:

In [29]:
m = np.array([[1, 2],[3, 4]])
m

array([[1, 2],
       [3, 4]])

In [30]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [31]:
m/2

array([[0.5, 1. ],
       [1.5, 2. ]])

#### 1.4. Inverse matrix and system of linear equations:

Calculating the inverse matrix:

In [32]:
m = np.array([[1, 2],[3, 4]])
print(m, "\n")
minv = np.linalg.inv(m)
minv

[[1 2]
 [3 4]] 



array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
mres = np.dot(m, minv)
np.round(mres,2) 

array([[1., 0.],
       [0., 1.]])

System of linear equations (number of equations = number of unknowns):

In [69]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
print("A")
print(A)
print("\nb")
print(b)
Ainv = np.linalg.inv(A)
print("A.Ainv")
print(np.round(np.dot(A,Ainv), 5))
print("\nnp.dot(Ainv,b)")
print(np.dot(Ainv,b))

A
[[5 8]
 [6 4]]

b
[[30]
 [25]]
A.Ainv
[[1. 0.]
 [0. 1.]]

np.dot(Ainv,b)
[[2.85714286]
 [1.96428571]]


In [35]:
np.linalg.solve(A, b)

array([[2.85714286],
       [1.96428571]])